if (mouse_y_pos >= 428) next_block_y = 8;
else if (mouse_y_pos >= 374) next_block_y = 7;
else if (mouse_y_pos >= 320) next_block_y = 6;
else if (mouse_y_pos >= 268) next_block_y = 5;
else if (mouse_y_pos >= 214) next_block_y = 4;
else if (mouse_y_pos >= 160) next_block_y = 3;
else if (mouse_y_pos >= 108) next_block_y = 2;
else if (mouse_y_pos >= 54) next_block_y = 1;
else if (mouse_y_pos >= 0) next_block_y = 0;
else next_block_y = 9;
if (mouse_x_pos >= 588) next_block_x = 8;
else if (mouse_x_pos >= 534) next_block_x = 7;
else if (mouse_x_pos >= 480) next_block_x = 6;
else if (mouse_x_pos >= 428) next_block_x = 5;
else if (mouse_x_pos >= 374) next_block_x = 4;
else if (mouse_x_pos >= 320) next_block_x = 3;
else if (mouse_x_pos >= 268) next_block_x = 2;
else if (mouse_x_pos >= 214) next_block_x = 1;
else if (mouse_x_pos >= 160) next_block_x = 0;
else next_block_x = 9;
if (block_y == 8) block_y_pos = 428;
else if (block_y == 7) block_y_pos = 374;
else if (block_y == 6) block_y_pos = 320;
else if (block_y == 5) block_y_pos = 268;
else if (block_y == 4) block_y_pos = 214;
else if (block_y == 3) block_y_pos = 160;
else if (block_y == 2) block_y_pos = 108;
else if (block_y == 1) block_y_pos = 54;
else if (block_y == 0) block_y_pos = 0;
else block_y_pos = 0;
if (block_x == 8) block_x_pos = 588;
else if (block_x == 7) block_x_pos = 534;
else if (block_x == 6) block_x_pos = 480;
else if (block_x == 5) block_x_pos = 428;
else if (block_x == 4) block_x_pos = 374;
else if (block_x == 3) block_x_pos = 320;
else if (block_x == 2) block_x_pos = 268;
else if (block_x == 1) block_x_pos = 214;
else if (block_x == 0) block_x_pos = 160;
else block_x_pos = 0;
