# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/yuxun/Desktop/LDL_FinalProject_Sudoku/Sudoku_vivado/Sudoku_vivado.srcs/sources_1/ip/Num6_Mem_Gen/Num6_Mem_Gen.xci
# IP: The module: 'Num6_Mem_Gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yuxun/Desktop/LDL_FinalProject_Sudoku/Sudoku_vivado/Sudoku_vivado.gen/sources_1/ip/Num6_Mem_Gen/Num6_Mem_Gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Num6_Mem_Gen'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/yuxun/Desktop/LDL_FinalProject_Sudoku/Sudoku_vivado/Sudoku_vivado.srcs/sources_1/ip/Num6_Mem_Gen/Num6_Mem_Gen.xci
# IP: The module: 'Num6_Mem_Gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yuxun/Desktop/LDL_FinalProject_Sudoku/Sudoku_vivado/Sudoku_vivado.gen/sources_1/ip/Num6_Mem_Gen/Num6_Mem_Gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Num6_Mem_Gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
